version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - python -m pip install --upgrade pip

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

conda:
  environment: docs/environment.yml
