version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  jobs:
    pre_build:
      - python -m pip install --upgrade pip

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
