name: spurs2
channels:
<<<<<<< HEAD
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.12.0
  - pytorch-lightning=1.7.3
  - biopython=1.79
  - sphinx>=4.0.0,<6.0.0
  - sphinx-rtd-theme>=1.0.0
  - sphinx-autodoc-typehints>=1.19.5
  - pip
  - pip:
    - -r ../requirements.txt
    - -e .. 
=======
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Documentation dependencies
  - sphinx=5.3.0
  - sphinx-rtd-theme=2.0.0
  - sphinx-autodoc-typehints=1.19.5
  - myst-parser>=0.18.1
  
  # Basic dependencies for importing the package
  - pytorch=1.12.0
  - pytorch-lightning=1.7.3
  - hydra-core=1.2.0
  - biopython=1.79
  
  # Additional dependencies
  - pip
  - numpy
  - mock 
>>>>>>> 3b21f9ea77675ef6c7cc0e632c77811c5ce2c358
